Redux thunk implementation
tinatsina/react-bookstore pull request #4
Opened 2022-09-28 09:37 UTC by tinatsina

## Summary
- used `redux thunk` to make async API calls
- API calls had `3` main functions
    - addBook
    - deleteBook
    - fetchBooks
- the UI is updated upon each successful implementation

## Libraries 📚 used

1. Vanilla JS `fetch API`
2. React-redux `thunk middleware`
3. Book Store API

## ChangeLog
- `feature` ---> `development`

2022-09-28 09:56 UTC, Bondok6 requested changes
## Hi @tinatsina 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
- No Linter errors ✅
- Correct GitHub flow ✅
- Your repo is professional ✅
- Your README is professional ✅
- Well file structure ✅


## Required Changes ♻️
- [ ] _Check the comments under the review._ ⬇

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 09:56 UTC, Bondok6 commented on src/redux/books/books.js
> +  .then(() => dispatch(fetchBookList()));
- [ ] Great job here 💯 However, According to the requirements you should use [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) for making API calls, kindly update your methods using `createAsyncThunk` 💯 

![-5](https://user-images.githubusercontent.com/45231276/192748784-986d0380-4a8c-48d5-8dc6-d6f5db84e562.PNG)

> For example, It should be something like
```
// fetch book using createAsyncThunk
export const fetchBook = createAsyncThunk(
  'books/fetchBook',
  async () => {
    const response = await fetch(BASE_URL);
    const data = await response.json();
    return data;
  },
);
```

2022-09-28 09:56 UTC, Bondok6 commented on src/components/Books.js
> +  // console.log(state.books[0]['item2'][0].title);
- [ ] I think it would be better to remove unused code from your project rather than comment it out to keep your code clean and follow [the best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)💯

![image](https://user-images.githubusercontent.com/45231276/181750281-0d99a210-25c7-4b54-b455-141811a9c361.png)

2022-09-28 09:56 UTC, Bondok6 commented on src/redux/books/books.js
> +// export const deleteBook = (data) => ({ type: DEL_BOOK, data });
- [ ] I think it would be better to remove unused code from your project rather than comment it out to keep your code clean and follow [the best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)💯

![image](https://user-images.githubusercontent.com/45231276/181750281-0d99a210-25c7-4b54-b455-141811a9c361.png)

2022-09-29 04:07 UTC, tinatsina commented on src/redux/books/books.js
> +  .then(() => dispatch(fetchBookList()));
## 👍 Resolved
- used your recommendation and switched to `createAsyncThunk`
- changed all three actions

2022-09-29 04:08 UTC, tinatsina commented on src/components/Books.js
> +  // console.log(state.books[0]['item2'][0].title);
## Resolved 👍 
- deleted all commented code and cleaned up indentation
- thanks for noticing

2022-09-29 04:08 UTC, tinatsina commented on src/redux/books/books.js
> +// export const deleteBook = (data) => ({ type: DEL_BOOK, data });
## Resolved 👍 
- deleted all commented code and cleaned up indentation
- thanks for noticing

2022-09-29 04:22 UTC, Davidosky007 approved these changes
Hi @tinatsina 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 06:02 UTC, merged